### PR TITLE
add to_hash and formatted_iban_string

### PR DESCRIPTION
**Pull request by phoet**
i'm using your library, thanks for this, and i would like to add some contributions that i found useful.

i was a bit lazy and have 3 different changes within this PR, if that is an issue, i can definitively provide separate ones. i think the changes are minor, so i found it ok to do so to remove some overhead.

removing the dependency-constraints is something that helps contributors setting up the project.

the changes are be backwards compatible and self explenatory if you look into the spec.

if you would like me to add something to the readme, i would be glad to do so.

### CODE REVIEW

**Comment by phoet** [comment]
furtherhin i fixed some deprecation warnings and added the bank-name to the extended bank data.

**Comment by zaknafain** [comment]
Thanks for your work. Could you please split the up? I will see to them.

**Comment by phoet** [comment]
they kinda depend on eachother now. i could get rid of the dependencies stuff, but that would require you to merge #21 first.

**Comment by zaknafain** [comment]
Now, that I published a new patch version and added some code for version 0.4.0 you are welcome to rebase your request so I can see to it.

**Comment by phoet** [comment]
@zaknafain i rebased the changes on top of current master. please have another look.

**Comment by phoet** [comment]
thx for merging!

**Pull request merged**
